# $Id: Makefile.check 10924 2002-03-23 19:59:35Z vakatov $
# Author:  Denis Vakatov, NCBI 

include $(builddir)/Makefile.mk

all:
	-$(srcdir)/check.sh "$(signature)" $(MAKE) $(builddir) all   $(CHECK_ARG)

clean:
	 $(srcdir)/check.sh "$(signature)" $(MAKE) $(builddir) clean $(CHECK_ARG)

purge: clean
	 $(srcdir)/check.sh "$(signature)" $(MAKE) $(builddir) purge $(CHECK_ARG)
